"""
alter post options
"""
# Generated by Django 4.1.1 on 2022-10-04 02:17

from django.db import migrations


class Migration(migrations.Migration):
    """
    migration class
    """

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
