"""
alter comments
"""
# Generated by Django 4.1.1 on 2022-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    migration class
    """

    dependencies = [
        ('blog', '0004_remove_post_comments_comment_post_alter_comment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')],
            default='draft', help_text='Set to "published" to make this post publicly visible',
            max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(null=True, related_name='blog_posts', to='blog.topic'),
        ),
    ]
