# Generated by Django 4.1.1 on 2022-10-04 16:38
"""
Generated file
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migrations class
    """

    dependencies = [
        ('blog', '0005_alter_comment_approved_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Set to "published" to make this post publicly visible', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.topic'),
        ),
    ]
